export const GET = "GET";
export const POST = "POST";
export const PUT = "PUT";
export const DELETE = "DELETE";

export const FETCH_VEHICLES = "FETCH_VEHICLES";
export const GET_VEHICLES = "GET_VEHICLES";
export const VEHICLES_FAIL = "VEHICLES_FAIL";

export const SEARCH_VEHICLE = "SEARCH_VEHICLE";
export const CLEAR_SEARCH = "CLEAR_SEARCH";

export const GET_DEPARTMENTS = "GET_DEPARTMENTS";
export const DEPARTMENTS_FAIL = "DEPARTMENTS_FAIL";
export const GET_DEPARTMENTS_WITH_COUNTS = "GET_DEPARTMENTS_WITH_COUNTS";
export const FAIL_DEPARTMENTS_WITH_COUNTS = "FAIL_DEPARTMENTS_WITH_COUNTS";

export const ADD_VEHICLES = "ADD_VEHICLES";
export const DELETE_VEHICLES = "DELETE_VEHICLES";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"